# Generated by Django 5.2.17 on 2026-09-11 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_actionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_identifier', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rejeição de pipeline',
                'verbose_name_plural': 'Rejeições de pipeline',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_key', models.CharField(choices=[('orders', 'Pedidos')], max_length=64)),
                ('source_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('success', 'Concluída'), ('warning', 'Concluída com rejeições'), ('failed', 'Falhou')], default='running', max_length=16)),
                ('steps', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('records_received', models.PositiveIntegerField(default=0)),
                ('records_valid', models.PositiveIntegerField(default=0)),
                ('records_rejected', models.PositiveIntegerField(default=0)),
                ('records_loaded', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Execução de pipeline',
                'verbose_name_plural': 'Execuções de pipeline',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source_system',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source_system', 'external_id'), name='unique_order_source_external_id'),
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['pipeline_key', '-started_at'], name='ops_pipeline_key_started_idx'),
        ),
        migrations.AddField(
            model_name='pipelineissue',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='operations.pipelinerun'),
        ),
        migrations.AddIndex(
            model_name='pipelineissue',
            index=models.Index(fields=['run', 'id'], name='ops_issue_run_id_idx'),
        ),
    ]
